<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-01-24T19:17:28+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => '!dlebytes',
    'version_installed' => '5.7.5.5',
    'misc' => array(
        'access_entity_updated' => 1453649258,
        'latest_version' => '5.7.5.4',
        'do_page_reindex_check' => false,
    ),
);
