FROM busybox
MAINTAINER Satheeshkumar Manoharan  <infosatheesh2020@gmail.com>

# Create default content dirs
RUN mkdir -p /var/www/html/ && mkdir -p /var/lib/mysql

# commented SELinux context
#RUN chcon -Rt svirt_sandbox_file_t /var/www/html
