FROM busybox
MAINTAINER Satheeshkumar Manoharan  <infosatheesh2020@gmail.com>

# Create default content dirs
RUN mkdir -p /usr/local/apache2/concrete

# commented SELinux context
#RUN chcon -Rt svirt_sandbox_file_t /usr/local/apache2/concrete
